aim/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.utils import regex_helper

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reports/', include("reports.urls")),
]

reports/urls.py
from django.urls import path
from . import views


app_name = 'reports'

urlpatterns = [
    path('', views.index, name='index'),
    path('date/<report_date>', views.publisher, name='publisher'),
    path('source/<report_source>,<report_pub_name>,<report_date>',
         views.source, name='source')
]

reports/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, DateTimeField, DecimalField, FloatField, IntegerField

# Create your models here.


class Reports(models.Model):
    date = DateField()
    pub_name = CharField(max_length=50)
    source = CharField(max_length=50)
    clicks = IntegerField()
    revenue = DecimalField(max_digits=19, decimal_places=2)

    class Meta:
        verbose_name = "Report"
        verbose_name_plural = "Reports"

    def __str__(self) -> str:
        return self.pub_name

reports/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Sum
from .models import Reports

# Create your views here.
def index(request):
    reports = Reports.objects.all()
    reports = reports.filter().values('date').order_by(
        'date').annotate(clicks=Sum('clicks'), revenue=Sum('revenue'))
    return render(request, 'reports/index.html', {'reports': reports})


def publisher(request, report_date):
    reports = Reports.objects.all().filter(date=report_date)
    return render(request, 'reports/publisher.html', {'reports': reports})


def source(request, report_source, report_pub_name, report_date):
    reports = Reports.objects.all().filter(source=report_source, pub_name=report_pub_name, date=report_date).values('source').annotate(
        source_clicks=Sum('clicks'), source_revenue=Sum('revenue'))
    return render(request, 'reports/source.html', {'reports': reports})

reports/templates/reports/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Report by date</li>
        </ol>
    </nav>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Date</th>
                <th>Sum Revenue</th>
                <th>Sum Clicks</th>
            </tr>
        </thead>
        <tbody>
        {% for report in reports %}
            <tr>
                <td><a href="{% url 'reports:publisher' report.date %}">{{ report.date }}<a/></td>
                <td>$ {{ report.revenue|floatformat:2 }}</td>
                <td>{{ report.clicks|intcomma }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock  %}

reports/templates/reports/publisher.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/reports">Report by date</a></li>
        <li class="breadcrumb-item active" aria-current="page">Publishers</li>
        </ol>
    </nav>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Publisher Name</th>
                <th>Sum Revenue</th>
                <th>Sum Clicks</th>
            </tr>
        </thead>
        <tbody>
        {% for report in reports %}
            <tr>
                <td><a href="{% url 'reports:source' report.source report.pub_name report.date %}">{{ report.pub_name|title }}<a/></td>
                <td>$ {{ report.revenue|floatformat:2 }}</td>
                <td>{{ report.clicks|intcomma }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock  %}

reports/templates/reports/source.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/reports">Report by date</a></li>
        <li class="breadcrumb-item"><a href="{{ request.META.HTTP_REFERER }}">Publishers</a></li>
        <li class="breadcrumb-item active" aria-current="page">Sources</li>
        </ol>
    </nav>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Source</th>
                <th>Sum Revenue</th>
                <th>Sum Clicks</th>
            </tr>
        </thead>
        <tbody>
        {% for report in reports %}
            <tr>
                <td>{{ report.source|title }}<a/></td>
                <td>$ {{ report.source_revenue|floatformat:2 }}</td>
                <td>{{ report.source_clicks|intcomma }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>AIM</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">AIM Revenue Reports</a>
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'reports:index' %}">Reports</a>
{% endblock  %}